/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kyper

import kotlin.test.Test
import kotlin.test.assertTrue

class KyperTest {
    @Test fun someLibraryMethodReturnsTrue() {
//        val classUnderTest = Kyper()
//        assertTrue(classUnderTest, "someLibraryMethod should return 'true'")
    }
}
