# https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# https://help.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-gradle

name: Main workflow

on:
  push:
    branches:
      - main
    # Push events to matching v*, i.e. v1.0, v20.15.10
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build dokkaHtml --continue

      - name: Publish Unit Test Results
        # https://github.com/marketplace/actions/publish-unit-test-results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: build/test-results/**/*.xml

      - name: Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)

      - name: Publish to Maven Central
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          SIGNING_SECRET_KEY_RING_FILE="./secret-key.gpg"
          echo "${{ secrets.SIGNING_SECRET_KEY_RING_CONTENT }}" | base64 -di > "$SIGNING_SECRET_KEY_RING_FILE"
          echo "signing.secretKeyRingFile=$SIGNING_SECRET_KEY_RING_FILE" >> gradle.properties
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> gradle.properties
          echo "signing.password=${{ secrets.SIGNING_PASSWORD }}" >> gradle.properties
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --max-workers 1

      - uses: actions/upload-pages-artifact@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          path: build/dokka/html

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
